name: Build and deploy ASP.Net Core app to Azure Web App - tubarberia-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore TuBarberiaAPI/TuBarberiaAPI.csproj

      - name: Build with dotnet
        run: dotnet build TuBarberiaAPI/TuBarberiaAPI.csproj --configuration Release

      - name: Publish project
        run: dotnet publish TuBarberiaAPI/TuBarberiaAPI.csproj -c Release -o publish_output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: publish_output

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5FB25E93589C4D899ABB2F21B7B19693 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CB4FAD3F6A034823B1420FDA1827890D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F9AECBBCF9E44AAEA745D6CF9A8288B5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tubarberia-api'
          slot-name: 'Production'
          package: .
